#pragma once

#define STRINGIGY(macro) #macro
#define STRINGIGY2(macro) STRINGIGY(macro)

#define FONTDEF_VERSION_MAJOR 1
#define FONTDEF_VERSION_MINOR 1
#define FONTDEF_VERSION_BUGFIX 0

#define FONTDEF_VERSION_STR \
    STRINGIGY2(FONTDEF_VERSION_MAJOR) "." \
    STRINGIGY2(FONTDEF_VERSION_MINOR) "-" \
    STRINGIGY2(FONTDEF_VERSION_BUGFIX)

